
# Prometheus configuration
prometheus:
  service:
    type: NodePort
    nodePort: 30003
  # prometheusSpec:
  #   # Service discovery configuration
  #   serviceMonitorSelector:
  #     matchLabels:
  #       app.kubernetes.io/instance: prom-stack

    # Resource limits
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels:
          app.kubernetes.io/instance: prom-stack

# Grafana configuration
grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 30002
  # Pre-configure data sources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prom-stack-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: false



# Node exporter (for node metrics)
nodeExporter:
  enabled: true

# kube-state-metrics (for Kubernetes metrics)
kubeStateMetrics:
  enabled: true

# Prometheus operator
prometheusOperator:
  enabled: true
