# ServiceMonitor for Node.js Application
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-stack-kube-nodejs-monitor
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prom-stack
    release: prom-stack
spec:
  namespaceSelector:
    matchNames:
    - nodejs-app
  selector:
    matchLabels:
      app: nodejs-app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---

# ServiceMonitor for Redis
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-stack-kube-redis-monitor
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prom-stack
    release: prom-stack
spec:
  namespaceSelector:
    matchNames:
    - nodejs-app
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
# ServiceMonitor for MongoDB
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-stack-kube-mongo-monitor
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prom-stack
    release: prom-stack
spec:
  namespaceSelector:
    matchNames:
    - nodejs-app
  selector:
    matchLabels:
      app: mongodb
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
