{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "{{ .Values.mongodb.auth.rootUsername }}"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "{{ .Values.mongodb.auth.rootPassword }}"
        - name: MONGO_INITDB_DATABASE
          value: "{{ .Values.mongodb.auth.database }}"
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 12 }}
        {{- if .Values.mongodb.persistence.enabled }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        {{- end }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongodb-pvc
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
{{- if .Values.mongodb.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
