apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs-app-service
  labels:
    env: stage
spec:
  selector:
    app: nodejs-app
  ports:
    - name: metrics
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: {{ .Values.service.type }}
